In [3]:
import pandas as pd
df=pd.read_excel(r"D:\Desktop\New folder\Book1.xlsx")

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,AGE,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,NaN,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,32057,NaN,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,NaN,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,25929,NaN,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,NaN,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [6]:
df.isnull().sum().sum()

92586

In [ ]:
#category=Technology, segment=Consumer , Sales>2000 and age> 30 and less than 40

In [10]:
df1=df[(df['Category']=="Technology") & (df['Segment']=='Consumer') & (df['Sales']>2000)].head().reset_index()
df1

,index,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
2,4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
3,12,45794,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,26282,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.960,4,0.0,1151.4000,832.41,Critical
4,21,31784,CA-2011-154627,2011-10-29,2011-10-31,First Class,SA-20830,Sue Ann Reed,Consumer,27763,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.952,6,0.2,341.9940,752.51,High

In [ ]:
df['new_qty']=df[Quantity]+7

In [12]:
# profit>3000- Hight profit
# profit>1000 and < 3000 mid_profit
# profit <1000 then less_profit

8399.976

In [17]:
df['Profit_tag']="Hight_profit"
df['Profit_tag'][df['Profit'].between(1000,3000)]="Mid_profit"
df['Profit_tag'][df['Profit']<1000]="Less_profit"

df['Profit_tag'].value_counts()

C:\Users\91824\AppData\Local\Temp\ipykernel_3412\876421222.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit_tag'][df['Profit'].between(1000,3000)]="Mid_profit"
C:\Users\91824\AppData\Local\Temp\ipykernel_3412\876421222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit_tag'][df['Profit']<1000]="Less_profit"

Less_profit     51143
Mid_profit        139
Hight_profit        8
Name: Profit_tag, dtype: int64

In [18]:
df['Profit_tag1']="Less_profit"
df['Profit_tag1'][df['Profit']>3000]="High_profit"
df['Profit_tag1'][df['Profit'].between(1000,3000)]="mid_profit"
df

C:\Users\91824\AppData\Local\Temp\ipykernel_3412\856841263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit_tag1'][df['Profit']>3000]="High_profit"
C:\Users\91824\AppData\Local\Temp\ipykernel_3412\856841263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit_tag1'][df['Profit'].between(1000,3000)]="mid_profit"

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,AGE,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_tag,Profit_tag1
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,NaN,...,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical,Less_profit,Less_profit
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,32057,NaN,...,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,Less_profit,Less_profit
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,NaN,...,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,Less_profit,Less_profit
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,25929,NaN,...,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,Less_profit,Less_profit
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,NaN,...,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,Less_profit,Less_profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,30381,NaN,...,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium,Less_profit,Less_profit
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,26934,NaN,...,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium,Less_profit,Less_profit
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,33769,NaN,...,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High,Less_profit,Less_profit
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,32558,NaN,...,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium,Less_profit,Less_profit
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,27919,NaN,...,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High,Less_profit,Less_profit

In [20]:
# profit>3000 --"HIGH"
# Profit<3000---LOW
df['new_profit3']="High"
df['new_profit3'][df['Profit']<3000]="Low"
df

C:\Users\91824\AppData\Local\Temp\ipykernel_3412\2576625800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new_profit3'][df['Profit']<3000]="Low"

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,AGE,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_tag,Profit_tag1,new_profit3
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,NaN,...,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical,Less_profit,Less_profit,Low
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,32057,NaN,...,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,Less_profit,Less_profit,Low
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,NaN,...,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,Less_profit,Less_profit,Low
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,25929,NaN,...,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,Less_profit,Less_profit,Low
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,NaN,...,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,Less_profit,Less_profit,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,30381,NaN,...,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium,Less_profit,Less_profit,Low
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,26934,NaN,...,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium,Less_profit,Less_profit,Low
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,33769,NaN,...,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High,Less_profit,Less_profit,Low
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,32558,NaN,...,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium,Less_profit,Less_profit,Low
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,27919,NaN,...,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High,Less_profit,Less_profit,Low

In [24]:
import numpy as np

In [26]:
df['new_profit4']=np.where(df['Profit']>3000,"High","Low")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,AGE,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_tag,Profit_tag1,new_profit3,new_profit4
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,NaN,...,2309.650,7,0.0,762.1845,933.570,Critical,Less_profit,Less_profit,Low,Low
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,32057,NaN,...,3709.395,9,0.1,-288.7650,923.630,Critical,Less_profit,Less_profit,Low,Low
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,NaN,...,5175.171,9,0.1,919.9710,915.490,Medium,Less_profit,Less_profit,Low,Low
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,25929,NaN,...,2892.510,5,0.1,-96.5400,910.160,Medium,Less_profit,Less_profit,Low,Low
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,NaN,...,2832.960,8,0.0,311.5200,903.040,Critical,Less_profit,Less_profit,Low,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,30381,NaN,...,65.100,5,0.0,4.5000,0.010,Medium,Less_profit,Less_profit,Low,Low
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,26934,NaN,...,0.444,1,0.8,-1.1100,0.010,Medium,Less_profit,Less_profit,Low,Low
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,33769,NaN,...,22.920,3,0.0,11.2308,0.010,High,Less_profit,Less_profit,Low,Low
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,32558,NaN,...,13.440,2,0.0,2.4000,0.003,Medium,Less_profit,Less_profit,Low,Low
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,27919,NaN,...,61.380,3,0.0,1.8000,0.002,High,Less_profit,Less_profit,Low,Low

In [28]:
df2=df.drop(['Profit_tag1','new_profit3','new_profit4'],axis=1)
df2

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,DOB,AGE,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_tag
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,36363,NaN,...,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.570,Critical,Less_profit
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,32057,NaN,...,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,Less_profit
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,24725,NaN,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,Less_profit
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,25929,NaN,...,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,Less_profit
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,28240,NaN,...,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,Less_profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,30381,NaN,...,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium,Less_profit
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,26934,NaN,...,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium,Less_profit
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,33769,NaN,...,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High,Less_profit
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,32558,NaN,...,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium,Less_profit
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,27919,NaN,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High,Less_profit

In [56]:
df2[['Profit_tag','Segment']].value_counts()

Profit_tag    Segment
Less_profit   Consumer       26439
              Corporate      15385
              Home Office     9319
Mid_profit    Consumer          74
              Corporate         42
              Home Office       23
Hight_profit  Consumer           5
              Corporate          2
              Home Office        1
dtype: int64

In [60]:
df3=df.groupby(['Profit_tag','Segment']).agg({"Row ID":"count"}).rename(columns={'Row ID':'Count_of_rows'}).reset_index()
df3

     Profit_tag      Segment  Count_of_rows
0  Hight_profit     Consumer              5
1  Hight_profit    Corporate              2
2  Hight_profit  Home Office              1
3   Less_profit     Consumer          26439
4   Less_profit    Corporate          15385
5   Less_profit  Home Office           9319
6    Mid_profit     Consumer             74
7    Mid_profit    Corporate             42
8    Mid_profit  Home Office             23

In [38]:
# segment wise total sales
df4=df.groupby(['Segment']).agg({"Sales":"sum"})

df4

                    Sales
Segment
Consumer     6.507949e+06
Corporate    3.824698e+06
Home Office  2.309855e+06

In [50]:
df6=df.groupby(['Segment']).agg({"Sales":"sum",'Row ID':"count","Profit":'min',"Quantity":'max'})
dfel6.rename(columns={'Sales':'Total_sales','Row ID':'Count_of_row','Profit':'Min_Profit','Quantity':'Max_quantity'})
df6_to_excel()

              Total_sales  Count_of_row  Min_Profit  Max_quantity
Segment
Consumer     6.507949e+06         26518   -6599.978            14
Corporate    3.824698e+06         15429   -4088.376            14
Home Office  2.309855e+06          9343   -3399.980            14

In [48]:
df7=df.groupby(['Segment'],as_index=False).agg({"Sales":"sum",'Row ID':"count","Sales":'min',"Sales":'max'})

       Segment     Sales  Row ID
0     Consumer  13999.96   26518
1    Corporate  17499.95   15429
2  Home Office  22638.48    9343